name: issue-automation
permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  assignIssue:
    name: Assign Issue to Someone
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/pylance-release' && github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v3
      - name: Created internally
        id: internal
        env:
            ISSUE_OWNER: ${{github.event.issue.user.login}}
        run: |
          echo ::set-output name=result::$(node -p -e "['bschnurr', 'heejaechang', 'debonte', 'rchiodo', 'judej', 'StellaHuang95'].filter(item => process.env.ISSUE_OWNER.toLowerCase() === item.toLowerCase()).length > 0 ? 1 : 0")
        shell: bash
      - name: Should we proceed
        id: proceed
        env:
            ISSUE_LABELS: ${{toJson(github.event.issue.labels)}}
            ISSUE_ASSIGNEES: ${{toJson(github.event.issue.assignees)}}
            ISSUE_IS_INTERNAL: ${{steps.internal.outputs.result}}
        run: |
          echo ::set-output name=result::$(node -p -e "process.env.ISSUE_IS_INTERNAL === '0' && JSON.parse(process.env.ISSUE_ASSIGNEES).length === 0 ? 1 : 0")
        shell: bash
      - uses: lee-dohm/last-assigned@v1
        with:
          query: 'is:issue'
          token: ${{ secrets.GITHUB_TOKEN }}
        id: assigned
      - uses: lee-dohm/team-rotation@v1
        with:
          last: ${{ steps.assigned.outputs.last }}
          include: bschnurr debonte heejaechang StellaHuang95 rchiodo
        id: rotation
      - name: Tuesday (Jude)
        if: steps.proceed.outputs.result == 1
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['${{ steps.rotation.outputs.next }}']
            })
