name: issue-automation
permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  assignIssue:
    name: Assign Issue to Someone
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/pylance-release' && github.event.action == 'opened'
    steps:
      - name: Find last assigned
        id: assigned
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const issues = await github.rest.issues.listForRepo({
              state: 'all',
              assignee: '*',
              sort: 'updated',
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return issues.data.length > 0 ? issues.data[0].assignee.login : '';
      - name: Dump last assigned
        env:
          LAST_ASSIGNED: ${{ steps.assigned.outputs.result }}
        run: echo "$LAST_ASSIGNED"
      - uses: lee-dohm/team-rotation@v1
        with:
          last: ${{ steps.assigned.outputs.result }}
          include: bschnurr debonte heejaechang StellaHuang95 rchiodo
        id: rotation
      - name: Dump next in rotation
        env:
          NEXT_ROTATION: ${{ steps.rotation.outputs.next }}
        run: echo "$NEXT_ROTATION"        
      - name: Assign to next person
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['${{ steps.rotation.outputs.next }}']
            })
